apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-main-ingress
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/suscription
            pathType: Prefix
            backend:
              service:
                name: suscription
                port:
                  number: 80
#d                  