apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-main-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-app-svc
                port:
                  number: 80
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: vsee
                port:
                  number: 80
          - path: /api/suscription
            pathType: Prefix
            backend:
              service:
                name: suscription
                port:
                  number: 80